[unstable]
build-std = ["core", "compiler_builtins"]

[build]
rustflags = ["-C", "relocation-model=pic", "-C", "link-arg=-pie"]

[target.'cfg(any(target_arch = "riscv32", target_arch="riscv64"))']
rustflags = ["-C", "link-args=-Tsrc/hal/lds/riscv.lds"]
