[unstable]
build-std = ["core", "compiler_builtins"]

[build]
rustflags = ["-C", "relocation-model=pic", "-C", "link-arg=-pie"]

[target.riscv32i-unknown-none-elf]
runner = "qemu-system-riscv32 -bios none -machine virt -serial mon:stdio -nographic -kernel"
rustflags = ["-C", "link-args=-Tsrc/hal/lds/riscv.lds"]

[target.riscv32e-unknown-none-elf]
runner = "qemu-system-riscv32 -cpu rv32e,zicsr=true -bios none -machine virt -serial mon:stdio -nographic -kernel"
rustflags = ["-C", "link-args=-Tsrc/hal/lds/riscv.lds"]
